---
title: "ACES"
author: "Logan Edvalson"
date: "2/15/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r package install}
#BiocManager::install("msa")
#install.packages("plotly")

#install.packages("seqinr")
##Define novel Functions
convertConserve <- function(x) { #function for replacing ATGC with 1 and everything else with 0
 y <- rep(0, length(x))
 y[x %in% c("A", "C", "G", "T", "a", "c", "g", "t")] <- 1
 return(y)
}
movingAverageEN <- function(x, n = 500) { #takes a moving average of ten data points
 stats::filter(x, rep(1 / n, n), sides = 1)
}
seqExtract <- function(x, z) { #extracts the windows that are high conservation. x=conPosEN z=consensusVect
 y <- lapply(x, function(x){
 start <- x - 100
 end <- x
 paste0(z[start:end], collapse = "")})
 return(y)
}
```
```{r}
library(msa)
library(plotly)
library(seqinr)
alignRead <- readDNAStringSet("your_sequences.fasta")
alignment <- msa(alignRead)
consensus <- msaConsensusSequence(alignment, type = "upperlower", thresh =
c(100,90)) #Specify how stringent you want the consensus to be
consensusVect <- unlist(strsplit(consensus, split = NULL)) #converts consensus into dataframe
binaryCons <- convertConserve(consensusVect)
raVectEN <- as.vector(movingAverageEN(binaryCons))
raVectEN[is.na(raVectEN)] <- 0
raFrameEN <- data.frame(raVectEN, c(1:length(raVectEN)))
 colnamesEN <- c("100 pt Rolling Average", "N")
 colnames(raFrameEN) <- colnamesEN
#highConEN <- raFrameEN[raFrameEN$`100 pt Rolling Average` > 0.85, ]
conPosEN <- as.vector(highConEN$N)
barplot(raFrameEN$`100 pt Rolling Average`,
 names.arg = c(1:length(raFrameEN$`100 pt Rolling Average`)),
 xlab = "Frame Index", ylab = "Conservation Score", ylim=c(0,1))
```